<a href="https://colab.research.google.com/github/rona11-17/pytorch_tutorial/blob/main/Pytorch0_5_automaticDifferentiation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch入門5. 自動微分

---
## Automatic Differentiation with `torch.autograd`


In [3]:
%matplotlib inline

In [5]:
import torch

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [6]:
print('Gradient function for z =', z.grad_fn)
print('Gradient function for loss =', loss.grad_fn)

Gradient function for z = <AddBackward0 object at 0x7807da6a5c60>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7807da6a6cb0>


In [7]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0818, 0.2899, 0.0179],
        [0.0818, 0.2899, 0.0179],
        [0.0818, 0.2899, 0.0179],
        [0.0818, 0.2899, 0.0179],
        [0.0818, 0.2899, 0.0179]])
tensor([0.0818, 0.2899, 0.0179])


In [10]:
z = torch.matmul(x, w) + b
print(z.requires_grad)
with torch.no_grad():
  z = torch.matmul(x, w) + b
print(z.requires_grad)

True
False


In [11]:
z = torch.matmul(x, w) + b
z_det = z.detach()
print(z_det.requires_grad)

False


In [12]:
inp = torch.eye(5, requires_grad=True)
out = (inp+1).pow(2)
out.backward(torch.ones_like(inp), retain_graph=True)
print("First call\n", inp.grad)
out.backward(torch.ones_like(inp), retain_graph=True)
print("\nSecond call\n", inp.grad)
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print("\nCall after zeroing gradients\n", inp.grad)

First call
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])

Second call
 tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

Call after zeroing gradients
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
