<a href="https://colab.research.google.com/github/rona11-17/pytorch_tutorial/blob/main/1_Learning_Pytorch/Pytorch1_2_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd

In [1]:
%matplotlib inline

In [2]:
import torch

In [3]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
print(y.grad_fn)

In [6]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [7]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1 ))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [8]:
out.backward()

In [9]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [10]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [11]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
  y = y * 2

print(y)

tensor([-1483.4099,   300.5320,   406.5937], grad_fn=<MulBackward0>)


In [12]:
torch.sqrt(y[0]*y[0] + y[1]*y[1] + y[2]*y[2])

tensor(1567.2086, grad_fn=<SqrtBackward0>)

In [13]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [15]:
print("x: ", x)
print("y: ", y)
scale = y/x
print("倍数: ", scale)

x:  tensor([-1.4486,  0.2935,  0.3971], requires_grad=True)
y:  tensor([-1483.4099,   300.5320,   406.5937], grad_fn=<MulBackward0>)
倍数:  tensor([1024., 1024., 1024.], grad_fn=<DivBackward0>)


In [16]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
  print((x**2).requires_grad)

True
True
False


In [17]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
